MODEL:
  ARCHITECTURE: "TAN"
  TAN:
    NUM_CLIPS: 128
    JOINT_SPACE_SIZE: 256
    FEATPOOL:
      INPUT_SIZE: 4096
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      POOLING_COUNTS: [15,8,8,8]
    TEXT_ENCODER:
      QUERY_HIDDEN_SIZE: 512
      NAME: 'BERT'
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: False
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 8
    LOSS:
      MIN_IOU: 0.3
      MAX_IOU: 0.7
      NUM_POSTIVE_VIDEO_PROPOSAL: 3
      NEGATIVE_VIDEO_IOU: 0.7
      SENT_REMOVAL_IOU: 0.5
      PAIRWISE_SENT_WEIGHT: 0.0
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.0
      RANKING_WEIGHT: 0.0
DATASETS:
  NAME: "tacos"
  TRAIN: ("tacos_train",)
  TEST: ("tacos_test",)
  METRIC_TENSORBOARD: False
INPUT:
  NUM_PRE_CLIPS: 256
  PRE_QUERY_SIZE: 300
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  LR: 0.001
  BATCH_SIZE: 6
  MILESTONES: (140,)
  MAX_EPOCH: 300
  TEST_PERIOD: 30
  CHECKPOINT_PERIOD: 10
  RESUME: False
  RESUME_EPOCH: 4
  FREEZE_BERT: 0
  ONLY_IOU: 150
TEST:
  NMS_THRESH: 0.4
  BATCH_SIZE: 12

