MODEL:
  ARCHITECTURE: "TAN"
  TAN:
    NUM_CLIPS: 64
    JOINT_SPACE_SIZE: 256
    FEATPOOL:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 4
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15,8,8]
    TEXT_ENCODER:
      NAME: "BERT"
      QUERY_HIDDEN_SIZE: 512
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: False
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 9
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      PAIRWISE_SENT_WEIGHT: 0.0
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.4
      CONTRASTIVE_WEIGHT: 0.1
DATASETS:
  NAME: "activitynet"
  TRAIN: ("activitynet_train", )
  TEST: ("activitynet_test",)
  METRIC_TENSORBOARD: False
INPUT:
  NUM_PRE_CLIPS: 256
  PRE_QUERY_SIZE: 300
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0002
  BATCH_SIZE: 96
  MILESTONES: (6, 14)
  MAX_EPOCH: 26
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: True
  RESUME_EPOCH: 8
  FREEZE_BERT: 4
  ONLY_IOU: 7
  SKIP_TEST: 1
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 48
  CONTRASTIVE_SCORE_POW: 1.0
