MODEL:
  ARCHITECTURE: "TAN"
  TAN:
    NUM_CLIPS: 16
    JOINT_SPACE_SIZE: 256
    FEATPOOL:
      INPUT_SIZE: 4096
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 16
    FEAT2D:
      NAME: "conv"
      POOLING_COUNTS: [15]
    TEXT_ENCODER:
      NAME: "BERT"
      QUERY_HIDDEN_SIZE: 512
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: False
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 8
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.6
      SENT_REMOVAL_IOU: 0.5
      PAIRWISE_SENT_WEIGHT: 0.0
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.4
      CONTRASTIVE_WEIGHT: 0.05
DATASETS:
  NAME: "charades"
  TRAIN: ("charades_train", )
  TEST: ("charades_test",)
  METRIC_TENSORBOARD: False
INPUT:
  NUM_PRE_CLIPS: 256
  PRE_QUERY_SIZE: 300
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.00015
  BATCH_SIZE: 72
  MILESTONES: (7, 14)
  MAX_EPOCH: 30
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: True
  RESUME_EPOCH: 9
  FREEZE_BERT: 4
  ONLY_IOU: 8
  SKIP_TEST: 2
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 96
  CONTRASTIVE_SCORE_POW: 0.5
