MODEL:
  ARCHITECTURE: "TAN"
  TAN:
    NUM_CLIPS: 16
    JOINT_SPACE_SIZE: 256
    FEATPOOL:
      INPUT_SIZE: 4096  # 1024 for i3d, 4096 for vgg/c3d
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15]
    TEXT_ENCODER:
      NAME: "BERT"
      QUERY_HIDDEN_SIZE: 1024
      LSTM:
        NUM_LAYERS: 5
        BIDIRECTIONAL: True
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 8
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1   #0.1
      TAU_SENT: 0.1   #0.1
      MARGIN: 0.4   # 0.4
      CONTRASTIVE_WEIGHT: 0.05  #0.05
DATASETS:
  NAME: "charades"
  TRAIN: ("charades_train", )
  TEST: ("charades_test",)
  METRIC_TENSORBOARD: False
INPUT:
  NUM_PRE_CLIPS: 32
  PRE_QUERY_SIZE: 300
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 48
  MILESTONES: (8, 14)  # vgg (8, 13)
  MAX_EPOCH: 18
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 7
  FREEZE_BERT: 4  # vgg 4
  ONLY_IOU: 7  # vgg 7
  SKIP_TEST: 3
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 24
  CONTRASTIVE_SCORE_POW: 0.5
