MODEL:
  ARCHITECTURE: "TAN"
  TAN:
    NUM_CLIPS: 16
    JOINT_SPACE_SIZE: 256
    FEATPOOL:
      INPUT_SIZE: [1024, 1024]  # 1024 for i3d, 4096 for vgg/c3d
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15]
    TEXT_ENCODER:
      NAME: "BERT"
      QUERY_HIDDEN_SIZE: 1024
      LSTM:
        NUM_LAYERS: 5
        BIDIRECTIONAL: True
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 7
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.3
      MAX_IOU: 0.9
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1   #0.1
      TAU_SENT: 0.1   #0.1
      MARGIN: 0.4   # 0.4
      CONTRASTIVE_WEIGHT: 0.1  #0.05
DATASETS:
  NAME: "stvg"
  TRAIN: ("stvg_train", )
  TEST: ("stvg_val", )
  METRIC_TENSORBOARD: False
INPUT:
  NUM_PRE_CLIPS: 32
  PRE_QUERY_SIZE: 300
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 32
  MILESTONES: (11, 16)  # vgg (8, 13)
  MAX_EPOCH: 20
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 10
  FREEZE_BERT: 5  # vgg 4
  ONLY_IOU: 10  # vgg 7
  SKIP_TEST: 1
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 32
  CONTRASTIVE_SCORE_POW: 0.5
