MODEL:
  ARCHITECTURE: "TAN"
  TAN:
    NUM_CLIPS: 128
    JOINT_SPACE_SIZE: 256
    FEATPOOL:
      INPUT_SIZE: 4096
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15,8,8,8]
    TEXT_ENCODER:
      NAME: 'BERT'
      QUERY_HIDDEN_SIZE: 512
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: False
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 8
    LOSS:
      MIN_IOU: 0.3
      MAX_IOU: 0.7
      NUM_POSTIVE_VIDEO_PROPOSAL: 3
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.1
      CONTRASTIVE_WEIGHT: 0.1
DATASETS:
  NAME: "tacos"
  TRAIN: ("tacos_train",)
  TEST: ("tacos_test",)
  METRIC_TENSORBOARD: False
INPUT:
  NUM_PRE_CLIPS: 256
  PRE_QUERY_SIZE: 300
DATALOADER:
  NUM_WORKERS: 12
SOLVER:
  LR: 0.0015
  BATCH_SIZE: 4
  MILESTONES: (130, 190)
  MAX_EPOCH: 250
  TEST_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  RESUME: False
  RESUME_EPOCH: 101
  FREEZE_BERT: 40
  ONLY_IOU: 100
  SKIP_TEST: 30
TEST:
  NMS_THRESH: 0.4
  BATCH_SIZE: 8
  CONTRASTIVE_SCORE_POW: 0.5

